{
    'name': 'Car Booking',
    'version': '18.1',
    'depends': ['base','fleet','project',
                 'contacts', 'account','stock','sale'],
    'data': [
        'security/security.xml',
        'security/ir.model.access.csv',
        'views/menu.xml',
        'views/car_booking_views.xml',
        'views/res_company_view.xml',
        'views/res_partner_view.xml',
        'views/res_users_view.xml',
        'views/sale_order_line_view.xml',
        'views/account_move_view.xml',
        'data/car_extra_service_data.xml',
        'views/car_extra_service_view.xml',
        'views/booking_cities.xml',
        'views/fleet_vehicle.xml',
        'views/car_airport.xml',
        'views/car_booking_line_view.xml',
        'data/paper_format.xml',
        'reports/custom_quotation_template.xml',
        'reports/car_booking_quotation_template.xml',
        'reports/car_booking_invoice_template.xml',
        'report/car_booking_report.xml',
        # 'security/car_booking_security.xml'
    ],
    'assets': {
        'web.report_assets_common': [
            'aw_car_booking/static/src/css/car_booking_reports.css',
            'aw_car_booking/static/src/font/Droid Arabic Naskh Regular/Droid Arabic Naskh Regular.ttf',
        ],
    },
    'installable': True,
    'application': True,
    'license': 'LGPL-3',
}
